pipeline {
    agent any
    triggers {
        pollSCM('H/5 * * * *') // Poll every 5 minutes
    }
    stages {
        stage('Checkout SCM') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Anjalirajaramker/HyderabadExplorer.git'
            }
        }
        stage('Verify Frontend Files') {
            steps {
                dir('Devops') { // navigate to the folder containing HTML/CSS/JS
                    echo 'Listing frontend project files...'
                    bat 'dir' // Windows command
                    echo '✅ Frontend code checkout successful!'
                }
            }
        }
    }
}
