version: '3.9'
services:
  frontend:
    image: hyderabad-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8888:80"
    volumes:
      - ./Devops:/usr/share/nginx/html:cached
    restart: unless-stopped
